const types = {
  GET_CART_LIST_START: 'GET_CART_LIST_START',
  GET_CART_LIST_SUCCESS: 'GET_CART_LIST_SUCCESS',
  GET_CART_LIST_ERROR: 'GET_CART_LIST_ERROR',
  ADD_PRODUCT_TO_CART_START: 'ADD_PRODUCT_TO_CART_START',
  ADD_PRODUCT_TO_CART_SUCCESS: 'ADD_PRODUCT_TO_CART_SUCCESS',
  ADD_PRODUCT_TO_CART_ERROR: 'ADD_PRODUCT_TO_CART_ERROR',
  UPDATE_PRODUCT_CART_START: 'UPDATE_PRODUCT_CART_START',
  UPDATE_PRODUCT_CART_SUCCESS: 'UPDATE_PRODUCT_CART_SUCCESS',
  UPDATE_PRODUCT_CART_ERROR: 'UPDATE_PRODUCT_CART_ERROR',
};

export default types;
