const types = {
  GET_PRODUCT_LIST_START: 'GET_PRODUCT_LIST_START',
  GET_PRODUCT_LIST_SUCCESS: 'GET_PRODUCT_LIST_SUCCESS',
  GET_PRODUCT_LIST_ERROR: 'GET_PRODUCT_LIST_ERROR',
};

export default types;
